### ISSUE TITLE
Browser app not found event

### ISSUE THREAD

**Issue by ffelini** [taboola/taboola-android#11]
Would be nice to have a separate event about missing Chrome Custom Tabs and Browser.
We have users reports where nothing happens when clicking on the Ad.

We've investigated the logs and found out that this log often occurs
`openUrlInTabsOrBrowser :: failed to open url `.

Right now the presence of the browser logic is encapsulated in `OnClickHelper` which doesn't tell anything about this case to the outside world.
Users must see the cause why something is not working and we would like to show a toast message in this case.

Thanks

**Comment by tzahie** [comment]
please use last sdk version. should be fixed there
