### ISSUE TITLE
Compatibility with AndroidX

### ISSUE THREAD

**Issue by JanKn** [taboola/taboola-android#19]
There is a conflicting attribute "mode" defined in Taboola SDK used on TaboolaWidget,  which also exists in AndroidX support libraries.
App then fails merging the resources during compilation.
Can you please rename the attribute to something more specific?

```
Android resource compilation failed
Output:  ...\build\intermediates\incremental\mergeGooglePlayDebugResources\merged.dir\values\values.xml:3211: error: duplicate value for resource 'attr/mode' with config ''.
...\build\intermediates\incremental\mergeGooglePlayDebugResources\merged.dir\values\values.xml:3211: error: resource previously defined here.

Command: ...\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\1ffcd11d11488b63a89f5568e83f449f\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        ...\build\intermediates\res\merged\googlePlay\debug \
        ...\build\intermediates\incremental\mergeGooglePlayDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
```

**Comment by omriariav** [comment]
Hi @JanKn - we are looking into this. thank you for letting us know

**Comment by JanKn** [comment]
Hi, any movement on this? 
It is the only blocker for us to update to AndroidX. There are some libraries coming, which require us to update already.
Thanks.

**Comment by omriariav** [comment]
Hi @JanKn ! We plan to release a SDK version that supports AndroidX by early January (we already communicated this ETA to your peers)

**Comment by omriariav** [comment]
The issue is caused by the androidx constraintlayout library version 2.0.0-alpah. Our SDK supports only stable androidx libraries.. as discussed, we recommend using version 1.1.3 for now until 2.0.0 matures out of alpha.
