### ISSUE TITLE
Support for Day Night Mode

### ISSUE THREAD

**Issue by jacksonej** [taboola/taboola-android#2]
Does the taboola widget support day-night mode ?

**Comment by shlomiaf** [comment]
Hi @jacksonej , what do you mean by "day-night mode" ?

**Comment by jacksonej** [comment]
After the release of AppCompat 23.2.0, now has a new theme family: Theme.AppCompat.DayNight.

So we are implementing this feature in our app. if we can also enable the dark theme to taboola ads that would be very helpful for our UI. So if there any support for this?

**Comment by shlomiaf** [comment]
@jacksonej Taboola widget look&feel is determined in advance by the Taboola server.  If you wish to create a custom look&feel to match your app, that should be defined on the server side. Your Taboola contact person would love to help with that.
