### ISSUE TITLE
GLHelper:  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Smbat888** [taboola/taboola-android#21]
Hey! I hope you are doing well!

We've found a crash in our Crashlytics reports and it was happening several times. Please see the description of the issue:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference

com.taboola.android.GLHelper$ClearRenderer$1.run + 54 (GLHelper.java:54)

Can you please fix this?

Thanks in advance

**Comment by omriariav** [comment]
@Smbat888 Thank you for reaching out.
This Github repo is no longer maintained as we moved our documentation to a new website: https://sdk.taboola.com - you can find there the documentation you need and a support forum for this kind of questions

About the issue, we're familiar with this NullPointerException and we already fixed that in Android SDK version 2.3.5. See here: https://sdk.taboola.com/taboolasdk/docs/taboola-android-sdk-changelog#section-235-2019-09-24
