### ISSUE TITLE
TaboolaApi use NULLABLE response body leads to NullPointerException

### ISSUE THREAD

**Issue by OneLiteCore** [taboola/taboola-android#5]
Sorry for decompiled your aar, but this problem really troubled me for a long time.

![taboola_use_nullable_body](https://user-images.githubusercontent.com/16048187/35432633-9e043c10-02bb-11e8-99b2-1581b518ee36.png)

As you can see in the screenshot, you call `body.getPlacementsMap()` to get some data without checking if the `body` is null, and this may lead to NullPointerException sometime.

Here is some source code from [retorfit2: retrofit/retrofit/src/main/java/retrofit2/Response.java](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Response.java), shows that Method `Response.body()` is marked as **@Nullable**:

```java
public final class Response<T> {

  //....Some other code

  /** The deserialized response body of a {@linkplain #isSuccessful() successful} response. */
  public @Nullable T body() {
    return body;
  }
}
```

Could you please fix it, T_T?

**Comment by dimanem** [comment]
Hey @DrkCore , we placed a guard there in the new version 1.3.3.

**Comment by OneLiteCore** [comment]
Glad to hear that, thanks!
